version: '3.8'
services:
  service1:
    image: shrutilende/application:latest
    build: ./service1
    container_name: flask_app
    restart: always
    depends_on:
      - service2
    ports:
      - "5100:5100"
    environment:
      FLASK_ENV: production

  service2:
    build: ./service2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: image_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
